trace:
  endpoint: http://192.168.21.205:14268/api/traces
server:
  http:
    addr: 0.0.0.0:0
    timeout: 1s
  grpc:
    addr: 0.0.0.0:0
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/doyle_blog?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.21.205:6379
    read_timeout: 0.2s
    write_timeout: 0.2s