// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"dy201.com/doyle-blog/app/blog/admin/internal/biz"
	"dy201.com/doyle-blog/app/blog/admin/internal/config"
	"dy201.com/doyle-blog/app/blog/admin/internal/data"
	"dy201.com/doyle-blog/app/blog/admin/internal/server"
	"dy201.com/doyle-blog/app/blog/admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	discovery := server.NewDiscovery(registry)
	userServiceClient := data.NewUserServiceClient(discovery, tracerProvider)
	dataData, err := data.NewData(confData, logger, userServiceClient)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger, userServiceClient)
	blogAdminServer := service.NewBlogAdminServer(userUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, logger, tracerProvider, blogAdminServer)
	grpcServer := server.NewGRPCServer(confServer, logger, tracerProvider, blogAdminServer)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
